production:
  sessions:
    default:
      database: twisent_production
      hosts:
        - localhost:27017
      username: efremov_dm
      password: MESqueUNClubf00B$R
      options:
  options:
    include_root_in_json: true

development:
  sessions:
    default:
      database: twitter_sentiments_development
      hosts:
        - localhost:27017
      options:
        
  options:
    use_activesupport_time_zone: true
test:
  sessions:
    default:
      database: twitter_sentiments_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

